[project]
name = "SPACE_JUMP"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "platformdirs>=4.9.4",
    "pygame>=2.6.1",
]

[project.scripts]
SPACE_JUMP = "SPACE_JUMP:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
